<?php
/**
 * includes/lang.php
 * Простой переключатель языка сайта (РУС / УКР).
 * Использование: t('ключ') — выводит нужную строку в текущем языке.
 */

function currentLang(): string
{
    if (isset($_GET['lang']) && in_array($_GET['lang'], ['ru', 'ua'], true)) {
        $_SESSION['lang'] = $_GET['lang'];
    }
    return $_SESSION['lang'] ?? 'ru';
}

$GLOBALS['TRANSLATIONS'] = [
    'ru' => [
        'nav_about'        => 'О мне',
        'nav_reviews'      => 'Отзывы',
        'nav_price'        => 'Прайс',
        'nav_booking'      => 'Запись',
        'about_empty'      => 'Информация обо мне скоро появится здесь.',
        'hero_eyebrow'     => 'Добро пожаловать',
        'hero_text'        => 'Здесь вы можете почитать отзывы, посмотреть актуальный прайс и записаться на удобное время.',
        'greet_title'      => 'Как к вам обращаться?',
        'greet_text'       => 'Чтобы мы могли обратиться к вам по имени 🙂',
        'greet_placeholder'=> 'Например, Мия',
        'greet_continue'   => 'Продолжить',
        'greet_skip'       => 'Пропустить',
        'greet_hello'      => 'Здравствуйте, %s!',

        'reviews_title'    => 'Отзывы',
        'reviews_empty'    => 'Пока нет отзывов — станьте первым!',
        'reviews_leave'    => 'Оставить отзыв',
        'reviews_name'     => 'Ваше имя',
        'reviews_rating'   => 'Оценка',
        'reviews_text'     => 'Отзыв',
        'reviews_photo'    => 'Фото (необязательно)',
        'reviews_send'     => 'Отправить отзыв',
        'reviews_sent'     => 'Спасибо! Ваш отзыв уже опубликован на сайте.',
        'reviews_count_word' => 'отзывов',
        'reviews_sort_label' => 'Сортировать:',
        'reviews_sort_new'   => 'Сначала новые',
        'reviews_sort_old'   => 'Сначала старые',
        'reviews_sort_rating_high' => 'Сначала с высокой оценкой',
        'reviews_sort_rating_low'  => 'Сначала с низкой оценкой',

        'price_title'      => 'Прайс',
        'price_subtitle'   => 'Маникюр и Педикюр',
        'price_empty'      => 'Прайс скоро появится.',
        'price_designs'    => 'Дизайны от 15 до 100 грн',
        'price_location'   => 'Ст. м. ХТЗ',

        'booking_title'    => 'Запись',
        'booking_intro'    => 'Выберите удобное свободное время в календаре, а затем напишите мастеру в любом удобном мессенджере — всё запишем и подтвердим.',
        'booking_selected' => 'Вы выбрали: ',
        'booking_none'     => 'Время пока не выбрано',
        'booking_cta'      => 'Записаться',
        'booking_contacts_title' => 'Напишите мастеру, чтобы подтвердить запись',
        'booking_contacts_hint'  => 'Сообщите выбранное время удобным способом:',
        'booking_instagram'=> 'Instagram',
        'booking_viber'    => 'Viber',
        'booking_telegram' => 'Telegram',
        'booking_phone'    => 'Позвонить',
        'booking_no_slots' => 'На эту неделю свободного времени пока нет',
        'booking_slot_booked' => 'занято',
        'booking_sent'     => 'Заявка отправлена! Мы свяжемся с вами для подтверждения.',

        'weekdays' => ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
        'months'   => ['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'],

        'fab_title'   => 'Связаться с мастером',
        'fab_master_name' => 'Мастер: Любовь',
        'fab_hint'    => 'Выберите удобный способ связи:',
        'close'       => 'Закрыть',

        'week_prev' => 'Предыдущая неделя',
        'week_next' => 'Следующая неделя',
        'reviews_photo_hint' => 'Можно прикрепить до 3 фото',
        'photo_view_alt' => 'Открыть фото',

        'booking_confirm_title'    => 'Подтвердите запись',
        'booking_confirm_question'=> 'Вы действительно хотите выбрать это время?',
        'yes'                      => 'Да',
        'no'                       => 'Нет',

        'admin_panel_button' => 'Панель управления',
        'admin_mode_badge'   => 'Режим администратора',

        'reviews_hide'    => '🙈',
        'reviews_show'    => '👁️',
        'reviews_delete'  => '🗑️',
        'reviews_hidden'  => 'Скрыт',
        'reviews_confirm_delete' => 'Удалить этот отзыв?',
        'reviews_edit_title'  => 'Редактировать отзыв',
        'reviews_edit_submit' => 'Сохранить изменения',

        'price_add_btn'     => 'Добавить позицию',
        'price_edit'        => '✏️',
        'price_delete'      => '🗑️',
        'price_confirm_delete' => 'Удалить эту позицию?',
        'price_form_title'  => 'Позиция прайса',
        'price_category_ru' => 'Категория (рус.)',
        'price_category_ua' => 'Категория (укр., необязательно)',
        'price_title_ru'    => 'Название услуги (рус.)',
        'price_title_ua'    => 'Название услуги (укр., необязательно)',
        'price_amount'      => 'Цена',
        'save'              => 'Сохранить',
        'cancel'            => 'Отмена',

        'slot_add_btn'       => 'Добавить время',
        'slot_form_title'    => 'Свободное время',
        'slot_date'          => 'Дата',
        'slot_time'          => 'Время',
        'slot_status'        => 'Статус',
        'slot_status_free'   => 'Свободно',
        'slot_status_booked' => 'Занято',
        'slot_delete'        => 'Удалить',
        'slot_confirm_delete'=> 'Удалить это время из календаря?',

        'about_view_work'    => 'Смотреть работы',
        'about_get_in_touch' => 'Связаться',
        'experience_title'   => 'Опыт работы',
        'widgets_title_default' => 'Галерея',
        'social_title'       => 'Соцсети',

        // ===== Анкета записи (модальное окно) =====
        'booking_form_title'         => 'Анкета записи',
        'booking_form_time_label'    => 'Выбранное время:',
        'booking_form_name'          => 'Имя',
        'booking_form_phone'         => 'Номер телефона',
        'booking_form_services'      => 'Выберите услуги',
        'booking_form_manicure'      => 'Маникюр',
        'booking_form_pedicure'      => 'Педикюр',
        'booking_form_extra'         => 'Дополнительно',
        'booking_form_service_none'  => '— не нужно —',
        'booking_form_contact_title' => 'Как с вами удобнее связаться?',
        'booking_form_contact_call'  => 'Звонок',
        'booking_form_submit'        => 'Подтвердить запись',
        'booking_form_service_error' => 'Выберите хотя бы одну услугу.',
        'booking_success_title'      => 'Запись успешно создана!',
        'booking_success_text'       => 'Мастер свяжется с вами в ближайшее время.',
        'booking_form_error_generic' => 'Не получилось отправить заявку, попробуйте ещё раз.',

        // ===== Мини-профиль клиента (шапка сайта) =====
        'profile_login_label'   => 'Логин:',
        'profile_status_title'  => 'Текущая запись',
        'profile_status_empty'  => 'Активных записей пока нет',
        'profile_change_photo'  => 'Изменить фото',
        'profile_logout'        => 'Выйти',

        // ===== Отдельная страница профиля (profile.php) =====
        'profile_page_title'      => 'Мой профиль',
        'profile_back_to_site'    => '← На сайт',
        'profile_bookings_title'  => 'Мои записи',
        'profile_no_bookings'     => 'Пока нет ни одной записи — выберите время во вкладке «Запись».',
        'booking_number_prefix'   => 'Запись №',
        'booking_card_time_label'    => 'Время:',
        'booking_card_services_label'=> 'Услуги:',
        'booking_card_master_phone'  => 'Телефон мастера:',
        'booking_card_address'       => 'Адрес:',
        'booking_card_address_empty' => 'Уточняется у мастера',
    ],
    'ua' => [
        'nav_about'        => 'Про мене',
        'nav_reviews'      => 'Відгуки',
        'nav_price'        => 'Прайс',
        'nav_booking'      => 'Запис',
        'about_empty'      => 'Інформація про мене скоро з\'явиться тут.',
        'hero_eyebrow'     => 'Ласкаво просимо',
        'hero_text'        => 'Тут ви можете прочитати відгуки, переглянути актуальний прайс і записатися на зручний час.',
        'greet_title'      => 'Як до вас звертатися?',
        'greet_text'       => 'Щоб ми могли звернутися до вас на ім\'я 🙂',
        'greet_placeholder'=> 'Наприклад, Мія',
        'greet_continue'   => 'Продовжити',
        'greet_skip'       => 'Пропустити',
        'greet_hello'      => 'Вітаємо, %s!',

        'reviews_title'    => 'Відгуки',
        'reviews_empty'    => 'Поки що немає відгуків — станьте першим!',
        'reviews_leave'    => 'Залишити відгук',
        'reviews_name'     => 'Ваше ім\'я',
        'reviews_rating'   => 'Оцінка',
        'reviews_text'     => 'Відгук',
        'reviews_photo'    => 'Фото (необов\'язково)',
        'reviews_send'     => 'Надіслати відгук',
        'reviews_sent'     => 'Дякуємо! Ваш відгук вже опубліковано на сайті.',
        'reviews_count_word' => 'відгуків',
        'reviews_sort_label' => 'Сортувати:',
        'reviews_sort_new'   => 'Спочатку нові',
        'reviews_sort_old'   => 'Спочатку старі',
        'reviews_sort_rating_high' => 'Спочатку з високою оцінкою',
        'reviews_sort_rating_low'  => 'Спочатку з низькою оцінкою',

        'price_title'      => 'Прайс',
        'price_subtitle'   => 'Манікюр та Педикюр',
        'price_empty'      => 'Прайс скоро з\'явиться.',
        'price_designs'    => 'Дизайни від 15 до 100 грн',
        'price_location'   => 'Ст. м. ХТЗ',

        'booking_title'    => 'Запис',
        'booking_intro'    => 'Оберіть зручний вільний час у календарі, а потім напишіть майстру у будь-якому зручному месенджері — все запишемо і підтвердимо.',
        'booking_selected' => 'Ви обрали: ',
        'booking_none'     => 'Час поки не обрано',
        'booking_cta'      => 'Записатися',
        'booking_contacts_title' => 'Напишіть майстру, щоб підтвердити запис',
        'booking_contacts_hint'  => 'Повідомте обраний час зручним способом:',
        'booking_instagram'=> 'Instagram',
        'booking_viber'    => 'Viber',
        'booking_telegram' => 'Telegram',
        'booking_phone'    => 'Подзвонити',
        'booking_no_slots' => 'На цей тиждень вільного часу поки немає',
        'booking_slot_booked' => 'зайнято',
        'booking_sent'     => 'Заявку надіслано! Ми зв\'яжемося з вами для підтвердження.',

        'weekdays' => ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд'],
        'months'   => ['січня','лютого','березня','квітня','травня','червня','липня','серпня','вересня','жовтня','листопада','грудня'],

        'fab_title'   => "Зв'язатися з майстром",
        'fab_master_name' => 'Майстер: Любов',
        'fab_hint'    => 'Оберіть зручний спосіб зв\'язку:',
        'close'       => 'Закрити',

        'week_prev' => 'Попередній тиждень',
        'week_next' => 'Наступний тиждень',
        'reviews_photo_hint' => 'Можна прикріпити до 3 фото',
        'photo_view_alt' => 'Відкрити фото',

        'booking_confirm_title'    => 'Підтвердіть запис',
        'booking_confirm_question'=> 'Ви дійсно хочете обрати цей час?',
        'yes'                      => 'Так',
        'no'                       => 'Ні',

        'admin_panel_button' => 'Панель керування',
        'admin_mode_badge'   => 'Режим адміністратора',

        'reviews_hide'    => '🙈',
        'reviews_show'    => '👁️',
        'reviews_delete'  => '🗑️',
        'reviews_hidden'  => 'Приховано',
        'reviews_confirm_delete' => 'Видалити цей відгук?',
        'reviews_edit_title'  => 'Редагувати відгук',
        'reviews_edit_submit' => 'Зберегти зміни',

        'price_add_btn'     => 'Додати позицію',
        'price_edit'        => '✏️',
        'price_delete'      => '🗑️',
        'price_confirm_delete' => 'Видалити цю позицію?',
        'price_form_title'  => 'Позиція прайсу',
        'price_category_ru' => 'Категорія (рос.)',
        'price_category_ua' => 'Категорія (укр., необов\'язково)',
        'price_title_ru'    => 'Назва послуги (рос.)',
        'price_title_ua'    => 'Назва послуги (укр., необов\'язково)',
        'price_amount'      => 'Ціна',
        'save'              => 'Зберегти',
        'cancel'            => 'Скасувати',

        'slot_add_btn'       => 'Додати час',
        'slot_form_title'    => 'Вільний час',
        'slot_date'          => 'Дата',
        'slot_time'          => 'Час',
        'slot_status'        => 'Статус',
        'slot_status_free'   => 'Вільно',
        'slot_status_booked' => 'Зайнято',
        'slot_delete'        => 'Видалити',
        'slot_confirm_delete'=> 'Видалити цей час з календаря?',

        'about_view_work'    => 'Дивитись роботи',
        'about_get_in_touch' => "Зв'язатися",
        'experience_title'   => 'Досвід роботи',
        'widgets_title_default' => 'Галерея',
        'social_title'       => 'Соцмережі',

        // ===== Анкета запису (модальне вікно) =====
        'booking_form_title'         => 'Анкета запису',
        'booking_form_time_label'    => 'Обраний час:',
        'booking_form_name'          => "Ім'я",
        'booking_form_phone'         => 'Номер телефону',
        'booking_form_services'      => 'Оберіть послуги',
        'booking_form_manicure'      => 'Манікюр',
        'booking_form_pedicure'      => 'Педикюр',
        'booking_form_extra'         => 'Додатково',
        'booking_form_service_none'  => '— не потрібно —',
        'booking_form_contact_title' => 'Як з вами зручніше зв\'язатися?',
        'booking_form_contact_call'  => 'Дзвінок',
        'booking_form_submit'        => 'Підтвердити запис',
        'booking_form_service_error' => 'Оберіть хоча б одну послугу.',
        'booking_success_title'      => 'Запис успішно створено!',
        'booking_success_text'       => "Майстер зв'яжеться з вами найближчим часом.",
        'booking_form_error_generic' => 'Не вдалося надіслати заявку, спробуйте ще раз.',

        // ===== Міні-профіль клієнта (шапка сайту) =====
        'profile_login_label'   => 'Логін:',
        'profile_status_title'  => 'Поточний запис',
        'profile_status_empty'  => 'Активних записів поки немає',
        'profile_change_photo'  => 'Змінити фото',
        'profile_logout'        => 'Вийти',

        // ===== Окрема сторінка профілю (profile.php) =====
        'profile_page_title'      => 'Мій профіль',
        'profile_back_to_site'    => '← На сайт',
        'profile_bookings_title'  => 'Мої записи',
        'profile_no_bookings'     => 'Поки немає жодного запису — оберіть час у вкладці «Запис».',
        'booking_number_prefix'   => 'Запис №',
        'booking_card_time_label'    => 'Час:',
        'booking_card_services_label'=> 'Послуги:',
        'booking_card_master_phone'  => 'Телефон майстра:',
        'booking_card_address'       => 'Адреса:',
        'booking_card_address_empty' => 'Уточнюється у майстра',
    ],
];

function t(string $key)
{
    $lang = currentLang();
    return $GLOBALS['TRANSLATIONS'][$lang][$key] ?? $GLOBALS['TRANSLATIONS']['ru'][$key] ?? $key;
}
